apiVersion: config.openshift.io/v1
kind: InsightsDataGather
metadata:
  name: cluster
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-set: CustomNoUpgrade,DevPreviewNoUpgrade,TechPreviewNoUpgrade
    capability.openshift.io/name: Insights
    release.openshift.io/create-only: "true"
spec:
  gatherConfig:
    gatherers:
      mode: All
