apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-insights
  name: operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/single-node-developer: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-insights
  name: gather
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/single-node-developer: "true"
