
# Only the "operator" service account in the openshift-insights namespace
# can access the insights-runtime-extractor API
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-rbac-proxy
  namespace: openshift-insights
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-set: TechPreviewNoUpgrade
    capability.openshift.io/name: Insights
data:
  config.yaml: |+
    authorization:
      static:
        - path: /gather_runtime_info
          resourceRequest: false
          user:
            name: system:serviceaccount:openshift-insights:operator
          verb: get