apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: insights-runtime-extractor
  namespace: openshift-insights
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Insights
  labels:
    app.kubernetes.io/name: insights-runtime-extractor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: insights-runtime-extractor
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 33%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: insights-runtime-extractor
      annotations:
        openshift.io/required-scc: insights-runtime-extractor-scc
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        kubectl.kubernetes.io/default-container: extractor
    spec:
      serviceAccountName: insights-runtime-extractor-sa
      hostPID: true
      # Deploy the insights-runtime-extractor only on Linux worker nodes
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: openshift-user-critical
      containers:
        - name: kube-rbac-proxy
          image: quay.io/openshift/origin-kube-rbac-proxy:latest
          args:
            - '--secure-listen-address=:8443'
            - '--upstream=http://127.0.0.1:8000'
            - '--config-file=/etc/kube-rbac-proxy/config.yaml'
            - '--tls-cert-file=/etc/tls/private/tls.crt'
            - '--tls-private-key-file=/etc/tls/private/tls.key'
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /etc/tls/private
              name: insights-runtime-extractor-tls
            - mountPath: /etc/kube-rbac-proxy
              name: kube-rbac-proxy-cm
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
        - name: exporter
          image: quay.io/openshift/origin-insights-runtime-exporter:latest
          volumeMounts:
            - mountPath: /data
              name: data-volume
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources: 
            requests:
              cpu: 10m
              memory: 200Mi
        - name: extractor
          image: quay.io/openshift/origin-insights-runtime-extractor:latest
          env:
            - name: CONTAINER_RUNTIME_ENDPOINT
              value: unix:///crio.sock
          livenessProbe:
            exec:
              command:
                - crictl
                - info
              periodSeconds: 10
              failureThreshold: 2
          resources: 
            requests:
              cpu: 10m
              memory: 200Mi
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - CAP_SYS_ADMIN
          volumeMounts:
            - mountPath: /crio.sock
              name: crio-socket
            - mountPath: /data
              name: data-volume
      volumes:
        - name: crio-socket
          hostPath:
            path: /run/crio/crio.sock
            type: Socket
        - name: data-volume
          emptyDir: {}
        - name: kube-rbac-proxy-cm
          configMap:
            name: kube-rbac-proxy
        - name: insights-runtime-extractor-tls
          secret:
            secretName: insights-runtime-extractor-tls