kind: GenericOperatorConfig
apiVersion: operator.openshift.io/v1alpha1
leaderElection:
  disable: true
interval: "2h"
storagePath: /var/lib/insights-operator
endpoint: https://console.redhat.com/api/ingress/v1/upload
conditionalGathererEndpoint: https://console.redhat.com/api/gathering/v2/%s/gathering_rules
impersonate: system:serviceaccount:openshift-insights:gather
pull_report:
  endpoint: https://console.redhat.com/api/insights-results-aggregator/v2/cluster/%s/reports
  delay: "60s"
  timeout: "3000s"
  min_retry: "30s"
processingStatusEndpoint: https://console.redhat.com/api/insights-results-aggregator/v2/cluster/%s/request/%s/status
reportEndpointTechPreview: https://console.redhat.com/api/insights-results-aggregator/v2/cluster/%s/request/%s/report
ocm:
  scaEndpoint: https://api.openshift.com/api/accounts_mgmt/v1/certificates
  scaInterval: "8h"
  clusterTransferEndpoint: https://api.openshift.com/api/accounts_mgmt/v1/cluster_transfers/
  clusterTransferInterval: "12h"

